### ISSUE TITLE
Revert the "DOMString framerate" change from issue #12

### ISSUE THREAD

**Issue by jernoble** [w3c/media-capabilities#96]
The issue of accurately representing "rational integer" time values in JavaScript is much larger than frame rate, and we should push for a general solution.  Above and beyond this general objection, we shouldn't be adding any complicated string parsing logic to represent media times.  The current specification allows the following values as valid `framerate`s:

"1"
"1.5"
"3/2"

But it also considers the following as valid `framerate`s:

"1.5/1"
"3/0.5"

And given that the justification for doing this parsing was to ensure that values could be accurately compared to one another without floating-point rounding, the following (pseudocode) comparisons will all evaluate to false:

```
framerate(1) != framerate("1/1")
framerate(1.5) != framerate("2/1")
framerate("1.") != framerate("1")
framerate("1/1") != framerate("2/2")
```

So we should either completely revert the change, and return the following entry to the `VideoConfiguration` dictionary:

```
    required double framerate;
```

...until such a time where we have an actual "media time" value to be used in place of double.  Or, if we must provide a way to pass a rational value into this API (and I don't believe we do), we should revert the change as above and add an additional property:

```
    double framerateDenominator = 1;
```

**Comment by chcunningham** [comment]
Hey Jer, we chrome folks are open to the revert. Will need to be careful not to break anyone, but the string representation does not matter internally - it was always for javascript developers. See the arguments from @mwatson2 in Issue 12. @mwatson2, please chime in here.

**Comment by chcunningham** [comment]
@mwatson2 friendly ping.

@jernoble you mentioned f2f some abandoned effort to standardize a Rational type for javascript. Is there a public record of that? Longshot to revive?

**Comment by mwatson2** [comment]
The original arguments are still valid so I'm not really in favor of going back to a plain double, but I agree that the string fraction is awkward. A Rational type would be ideal, but otherwise could we have *integer* `frameRateNumerator` and `frameRateDenominator` ? Or at least `frameRateNumerator` could be required to be an integer when `frameRateDenominator` != 1.

There is the issue of nomalization: developers would have to take care of that themselves if they want to do comparisons, but I think that is fine: this is just a dictionary that they create with properties that just carry values they put there, so I think we can leave this to them.

**Comment by chcunningham** [comment]
@mwatson2, let me poke at the original argument a bit. In Issue #12 you wrote

> So, the problem is that the attribute is set to, say, (24000/1001) and later someone tries to compare it to 23.967. They are not equal, but the same frame rate is intended.

This is true, but I'm confused about how the change we made solves this problem. Now the user can set the string to "24000/1000", but it remains true that if someone later compares it to 23.967 the comparison will still be not equal.

**Comment by mwatson2** [comment]
@chcunningham Yes, so what is needed is a format that does not support decimals, only explicit fractions. At least users will know then that they're working with an exact fraction and they have to take care of normalization.

I guess the other - admittedly imprecise - point is that many years of painful experience in the video industry suggests it is more robust to identify frame rates (and indeed frame timestamps) in a unique and precise way, rather than having multiple imprecise values that are supposed to mean the same thing.

**Comment by cynthia** [comment]
Unless you are doing fractions of fractions, wouldn't that be possible to achieve with two ints?

**Comment by mwatson2** [comment]
@cynthia Yes, tow ints would be ideal.

**Comment by chcunningham** [comment]
Two ints is possible. Perhaps we could make the denominator default to 1 so folks who want to use whole numbers need only supply the numerator. @jernoble @mounirlamouri @jyavenard - thoughts?

**Comment by jernoble** [comment]
I think the numerator should be a `long long` And the denominator should be `unsigned long`, but apart from that minor nit, I’m very supportive of this idea!

I also think that the Rational(e?) class Is going to need a lot of standardization, especially around arithmetic but that’s a problem for a different spec.

**Comment by chcunningham** [comment]
> framerate will be of type any and in spec prose, we will only allow double or Rationale;

I feel like offering the flexibility for double or Rationale means we haven't solved the problem I described above with the current double or String approach. 

> Now the user can set the string to "24000/1000", but it remains true that if someone later compares it to 23.967 the comparison will still be not equal.

Per @mwatson2's original bug, we need a solution that prevents the mixing of rational and decimal representation.

**Comment by mounirlamouri** [comment]
We could have the `Rational` object be constructed with a `double` and have the `framerate` only take a `Rational`. I wonder if we would be optimising for the few by doing so but it's an option.

@jernoble regarding `long long` I have no strong preference but looking at different rational implementations in languages, I can't find any that requires the denominator to be positive and it's not mathematically needed either. Why would you like to see this change?

**Comment by jernoble** [comment]
> @jernoble regarding long long I have no strong preference but looking at different rational implementations in languages, I can't find any that requires the denominator to be positive and it's not mathematically needed either. Why would you like to see this change?

Only because it seems unnecessary and complicated to try to spec the behavior of {-1, -1} === {1, 1}. If this `Rational` object is cast-able to a double, then the spec is going to have to have to include a "normalization" step that would be unnecessary if the denominator was defined to be positive.

Is there any use case for a `Rational` that would require the denominator to be negative?

**Comment by jernoble** [comment]
...Also, I'm coming at this from the perspective of using this class to represent media time. As far as I'm aware, both ISO BMFF and Matroska (maybe OGG?) define their timescale values as unsigned integers. While a `Rational` class may have uses outside of media times, for the primary use case of the class, a signed denominator is not necessary, and may be confusing.

**Comment by mounirlamouri** [comment]
The goal here is to use this beyond media with a long term hope that it may show up as part of EcmaScript. I agree that for media, both numerator and denominator could simply be positive but in a maths context, I think it's unnecessary burden on the developer as we can easily check equality of things with double negatives and all.

We may simply require the Rational object (and the double) to be positive when passed to framerate and reject otherwise.

**Comment by chcunningham** [comment]
Sorry, didn't reply sooner - was hoping to hear from Mark.

> I don’t think that’s true. #12 was originally about precision, not mixing. We are describing the type of a dictionary entry which, unless the client retains it themselves, they will never see again. There is no “mixing” of types unless the client chooses to mix it.

I agree that 12 is initially about precision, but when asked to explain why precision mattered @mwatson2 explains that the current implementation makes it too easy for folks to mix values that are symbolically but not mathematically equivalent. Mark again makes this clear in [his comment above](https://github.com/WICG/media-capabilities/issues/96#issuecomment-434889897):

> what is needed is a format that does not support decimals, only explicit fractions. At least users will know then that they're working with an exact fraction and they have to take care of normalization.

Re: code example, I found Mark's [explanation here](https://github.com/WICG/media-capabilities/issues/12#issuecomment-292968136) straightforward enough. I also agree with @jernoble that this is not likely to be a common problem. Buuut, if we're going to move away from a simple double, I want to be sure we arrive at something that addresses the original report. Otherwise, just make it a double.

**Comment by jernoble** [comment]
@chcunningham, right, but I still don't understand how that mixing happens, nor how mandating a rational number solves it. This "timescale" value is (as far as I know!) never vended by any web API; it's an input only. So the only way for someone to "mix" types is if the caller themselves exposed these values directly. The simple answer there is: don't do that.  That's why I was hoping for sample code.

**Comment by jernoble** [comment]
(There's also the side note that "frame rate" can't necessarily be specified with any precision in digital media in the first place. Especially with ISO BMFF, the "duration" of a given frame can vary frame-by-frame, so the "number of frames" displayed in a given second will vary from second to second in such media. So I find this particular hill a weird one to die on. But since it aligns with my long-held opinions on the awfulness of using doubles for media time, I'm totally willing to charge up that hill too.)

**Comment by chcunningham** [comment]
In f2f meeting we (@jernoble @mounirlamouri @jyavenard) agreed to revert the string rational fps and simply use double. Accepting both string and double failed to resolve the initial issue from @mwatson2  and string is unpleasant for reasons Jer mentions above.

We also agreed that a standardized Rational type is desirable and would like a future where both double and Rational are accepted. This would still not resolve the initial issue from Mark, but its more natural for framerates that don't evenly divide.

**Comment by mwatson2** [comment]
I don't think we should give up trying to resolve the original issue I raised. All I can say is that inaccurate representation of rational quantities in media (frame rates and media timestamps for that matter) has - over the years I have worked on media systems - been the source of no end of problems, bugs, horrible work-arounds and confusion. I can count multiple issues just this year in Netflix caused by inaccurate representations. These are not in the web context, but I am just trying to illustrate the value of accurate representation rational quantities related to media.

For me, this value would justify a custom type for this purpose e.g. a frame rate type with numerator and denominator and compare() method, or an enumeration of the 8 or so frame rates that are actually in use.

**Comment by mounirlamouri** [comment]
I think we all think this should ideally be resolved but the core problem here is whether it's a urgent problem to solve. The way it was solved (parsing a DOMString) wasn't ideal. We reached out to some ECMAScript folks at Google and they mentioned that getting something like a Rational type out there would be doable but take time. If we feel that this is urgent because it's a top priority for our API, we could have a temporary solution but I don't think any implementation today would care much between the small differences it would create.

**Comment by mwatson2** [comment]
So, if the intention is to move to Rational of some form then it depends on what 'takes some time' means. If that Rational type is going to be available within the timeframe of the Media Working Group making this feature into a Candidate Recommendation, then fine, we can wait for that.

If it's going to be 2-3 years to get a Rational type then I think it's worth doing the accurate thing for that interim period. If implementations 'would not care much' then it should be easy.

**Comment by jernoble** [comment]
I still don't really understand the argument that we _must_ have an accurate representation of frame rate here. Will the answer given by the UA change based on floating point rounding? Doubtful.  As @mwatson2 suggests, there's only like "8 or so frame rates that are actually in use". UAs can be expected to figure this out.

**Comment by mwatson2** [comment]
@jernoble As I originally [wrote](https://github.com/w3c/media-capabilities/issues/12#issuecomment-292968136):
> There isn't a problem for simple queries, but I worry about people mistakenly relying on the value they read back from this attribute because, for example, 24000 / 1001 != 23.967. 

Once people are using the `VideoConfiguration` objects they are likely to pass them around and read back from them. The problem is that we're teaching people that a `double` is a good way to represent a frame rate when we know from years of hard-won experience that it is not.

For both Frame Rate and media timestamps I have seen any number of situations where it is argued that within some specific context, representing them inaccurately doesn't cause a functional problem. This can be true for that context, but then the inaccurate representation leaks into some other context or the pattern is copied etc. etc.

If there is a good reason why we should *not* use an accurate representation, that's one thing, but in the absence of that, surely we should do the right thing and represent it accurately with a rational or enum ?

Note that per the OP browsers supporting VP9 already in some context support the MPEG Codec-independent code point values used to represent frame rates in the VP9 `codecs` string. We could use that here too ...

**Comment by jernoble** [comment]
@mwatson2 and as I originally wrote:

> There's also the side note that "frame rate" can't necessarily be specified with any precision in digital media in the first place. Especially with ISO BMFF, the "duration" of a given frame can vary frame-by-frame, so the "number of frames" displayed in a given second will vary from second to second in such media. 

So the argument that it is vitally important to accurately represent frame rates at a greater-than-floating point level of precision doesn’t hold much water with me. _If_ there were a `Rational` number type available, I’d be open to using it here. But in its absence, `double` is good enough.

I’ve been yelling into the void about using rational number types for media timestamps for nearly a decade now, so please don’t misinterpret the above as callousness. But given your statement about how things “leak into some other context or the pattern is copied etc. etc.”, inventing something one-off” rational-in-a-string parsing mechanism is likely to do much more harm than good.

**Comment by mwatson2** [comment]
@jernoble We can join forces in the crusade for accurate media timestamps! Perhaps in another decade we will get there ...

I know ISOBMFF supports arbitrary frame timestamps but I'm not aware of that possibility being widely used. As far as I know, all TVs expect the media to be in one of the standard fixed frame rates and when needed they make explicit switches between frame rate that can take some time to execute.

Yes, a `double` is "good enough" for this specific context, but an accurate value would be better. I am also wondering about the transition (`changeType`) case. If we use a double, a UA that does *not* support transitions between streams at different frame rates should still indicate support for transition between frame rates provided as 23.976023976023978 and 23.976. That is, internally the UA will need a mapping between `double` frame rates and the 8ish standard values. Would we need to standardize that mapping ?

I take the point about the string format. I'm leaning most towards the enum at the moment, since it is already used on the platform in the `codec` strings.

**Comment by jernoble** [comment]
@mwatson2

> I know ISOBMFF supports arbitrary frame timestamps but I'm not aware of that possibility being widely used. 

I’ve definitely seen files with weird frame cadences; like (and this not exactly what I’ve seen but representative) on a timebase of 2400, having frames with durations of 99, 100, 100, 99, 100, 100. There are some freaky encoders out there and in the end, we play their files just fine.

> If we use a double, a UA that does not support transitions between streams at different frame rates should still indicate support for transition between frame rates provided as 23.976023976023978 and 23.976. 

And those same UAs have to know that they can transition from a frame rate of “24000/1001” and “48000/1001”.  If a UA really can’t support switching between a frame rate of “24000/1001” and “23976/1000”, then they’ll reject, as they should. I’m not sure such a UA exists or will exist, and if they do, they definitely can’t handle that weird-cadence ISO file I found earlier.

**Comment by mwatson2** [comment]
@jernoble I'm pretty sure that on a TV, the weird cadence file you gave as an example gets rendered at 24fps with frame drop every so often (as that example was in fact more than 24 fps).

If a device truly supports arbitrary cadence (that is, doesn't just render at closest standard rate with frame drops) and *also* has restricted frame rate switching (that is, support frame rate switching in some cases and not others), then that capability discovery is an exceptionally difficult problem, since it is very hard to characterize arbitrary cadences in a way that would enable you to capture all hypothetical restrictions. I would submit that the actually interesting case is the devices which lock to standard frame rates and those are the ones with restricted frame rate switching capability.

So, I just think we should have a canonical way of representing the standard frame rates. To do that with a rational is, I agree, a bit awkward (the numerator must be constrained to be a multiple of 1000 and the denominator constrained to be either 1000 or 1001). Doing it with a double is even harder. I would be fine with the type being `double | enum`.

**Comment by chcunningham** [comment]
Discussed at TPAC, resolved to proceed with the revert to a double. https://www.w3.org/2019/09/18-mediawg-minutes.html

Mark felt ratio representation was less critical upon noting that the framerate is not intended to be used determine supported=true/false. Its main purpose is to help make smooth=true/false predictions.
